## Consantes de los VO's

# Constantes de Tienda

TIENDA_ID = 'id'
TIENDA_CIUDAD = 'ciudad'
TIENDA_CODIGO = 'codigoPostal'
# Constantes de Cliente
CLIENTE_ID = 'id'
CLIENTE_EMAIL = 'email'
CLIENTE_PASSWORD = 'password'
CLIENTE_PASSWORD2 = 'password2'
CLIENTE_USUARIO = 'username'
TIENDA = 'tienda'


PRODUCTO = 'producto'
# Constantes de Consola
CONSOLA_ID = 'id'
CONSOLA_NOMBRE = 'nombre'
CONSOLA_DESCRIPCION = 'descripcion'
CONSOLA_VALORACION = 'valoracion'
CONSOLA_IMG = 'img'

# Constantes de Videojuego
VIDEOJUEGO_ID = 'id'
VIDEOJUEGO_NOMBRE = 'nombre'
VIDEOJUEGO_DESCRIPCION = 'descripcion'
VIDEOJUEGO_VALORACION = 'valoracion'
VIDEOJUEGO_PLATAFORMAS = 'plataformas'
VIDEOJUEGO_IMG = 'img'

# Constantes de ReservaConsola
FECHA = 'fecha'

# Constantes grupos
GRUPO_TRABAJADORES = 'Trabajador'
GRUPO_CLIENTES = 'Cliente'

# Constantes para codename de permisos
PERMISO_ADD_USUARIO = 'add_usuario'
PERMISO_CHANGE_USUARIO = 'change_usuario'
PERMISO_DELETE_USUARIO = 'delete_usuario'
PERMISO_VIEW_USUARIO = 'view_usuario'
PERMISOS_USUARIO = [PERMISO_ADD_USUARIO, PERMISO_CHANGE_USUARIO, PERMISO_DELETE_USUARIO, PERMISO_VIEW_USUARIO]


PERMISO_ADD_CONSOLA = 'add_consola'
PERMISO_CHANGE_CONSOLA = 'change_consola'
PERMISO_DELETE_CONSOLA = 'delete_consola'
PERMISO_VIEW_CONSOLA = 'view_consola'
PERMISOS_CONSOLA = [PERMISO_ADD_CONSOLA, PERMISO_CHANGE_CONSOLA, PERMISO_DELETE_CONSOLA, PERMISO_VIEW_CONSOLA]

PERMISO_ADD_STOCKCONSOLA = 'add_stockconsola'
PERMISO_CHANGE_STOCKCONSOLA = 'change_stockconsola'
PERMISO_DELETE_STOCKCONSOLA = 'delete_stockconsola'
PERMISO_VIEW_STOCKCONSOLA = 'view_stockconsola'
PERMISOS_STOCKCONSOLA = [PERMISO_ADD_STOCKCONSOLA, PERMISO_CHANGE_STOCKCONSOLA, PERMISO_DELETE_STOCKCONSOLA, PERMISO_VIEW_STOCKCONSOLA]

PERMISO_ADD_STOCKVIDEOJUEGO = 'add_stockvideojuego'
PERMISO_CHANGE_STOCKVIDEOJUEGO = 'change_stockvideojuego'
PERMISO_DELETE_STOCKVIDEOJUEGO = 'delete_stockvideojuego'
PERMISO_VIEW_STOCKVIDEOJUEGO = 'view_stockvideojuego'
PERMISOS_STOCKVIDEOJUEGO = [PERMISO_ADD_STOCKVIDEOJUEGO, PERMISO_CHANGE_STOCKVIDEOJUEGO, PERMISO_DELETE_STOCKVIDEOJUEGO, PERMISO_VIEW_STOCKVIDEOJUEGO]

PERMISO_ADD_VIDEOJUEGO = 'add_videojuego'
PERMISO_CHANGE_VIDEOJUEGO = 'change_videojuego'
PERMISO_DELETE_VIDEOJUEGO = 'delete_videojuego'
PERMISO_VIEW_VIDEOJUEGO = 'view_videojuego'
PERMISOS_VIDEOJUEGO = [PERMISO_ADD_VIDEOJUEGO, PERMISO_CHANGE_VIDEOJUEGO, PERMISO_DELETE_VIDEOJUEGO, PERMISO_VIEW_VIDEOJUEGO]


PERMISO_ADD_CLIENTE = 'add_cliente'
PERMISO_CHANGE_CLIENTE = 'change_cliente'
PERMISO_DELETE_CLIENTE = 'delete_cliente'
PERMISO_VIEW_CLIENTE = 'view_cliente'
PERMISOS_CLIENTE = [PERMISO_ADD_CLIENTE, PERMISO_CHANGE_CLIENTE, PERMISO_DELETE_CLIENTE, PERMISO_VIEW_CLIENTE]

PERMISO_ADD_TIENDA = 'add_tienda'
PERMISO_CHANGE_TIENDA = 'change_tienda'
PERMISO_DELETE_TIENDA = 'delete_tienda'
PERMISO_VIEW_TIENDA = 'view_tienda'
PERMISOS_TIENDA = [PERMISO_ADD_TIENDA, PERMISO_CHANGE_TIENDA, PERMISO_DELETE_TIENDA, PERMISO_VIEW_TIENDA]

PERMISO_ADD_RESERVAVIDEOJUEGO = 'add_reservavideojuego'
PERMISO_CHANGE_RESERVAVIDEOJUEGO = 'change_reservavideojuego'
PERMISO_DELETE_RESERVAVIDEOJUEGO = 'delete_reservavideojuego'
PERMISO_VIEW_RESERVAVIDEOJUEGO = 'view_reservavideojuego'
PERMISOS_RESERVAVIDEOJUEGO = [PERMISO_ADD_RESERVAVIDEOJUEGO, PERMISO_CHANGE_RESERVAVIDEOJUEGO, PERMISO_DELETE_RESERVAVIDEOJUEGO, PERMISO_VIEW_RESERVAVIDEOJUEGO]

PERMISO_ADD_RESERVACONSOLA = 'add_reservaconsola'
PERMISO_CHANGE_RESERVACONSOLA = 'change_reservaconsola'
PERMISO_DELETE_RESERVACONSOLA = 'delete_reservaconsola'
PERMISO_VIEW_RESERVACONSOLA = 'view_reservaconsola'
PERMISOS_RESERVACONSOLA = [PERMISO_ADD_RESERVACONSOLA, PERMISO_CHANGE_RESERVACONSOLA, PERMISO_DELETE_RESERVACONSOLA, PERMISO_VIEW_RESERVACONSOLA]

PERMISO_ADD_TRABAJADOR = 'add_trabajador'
PERMISO_CHANGE_TRABAJADOR = 'change_trabajador'
PERMISO_DELETE_TRABAJADOR = 'delete_trabajador'
PERMISO_VIEW_TRABAJADOR = 'view_trabajador'
PERMISOS_TRABAJADOR = [PERMISO_ADD_TRABAJADOR, PERMISO_CHANGE_TRABAJADOR, PERMISO_DELETE_TRABAJADOR, PERMISO_VIEW_TRABAJADOR]

def getPermisosTrabajador():
    listaPermisos = [PERMISO_VIEW_RESERVAVIDEOJUEGO, PERMISO_CHANGE_RESERVAVIDEOJUEGO, 
            PERMISO_VIEW_RESERVACONSOLA, PERMISO_CHANGE_RESERVACONSOLA]
    listaPermisos = listaPermisos + PERMISOS_CONSOLA + PERMISOS_STOCKCONSOLA + PERMISOS_STOCKVIDEOJUEGO + PERMISOS_VIDEOJUEGO
    return listaPermisos


def getPermisosCliente():
    listaPermisos = [PERMISO_VIEW_VIDEOJUEGO,
             PERMISO_VIEW_STOCKCONSOLA, PERMISO_VIEW_STOCKVIDEOJUEGO, PERMISO_VIEW_CONSOLA, PERMISO_VIEW_TIENDA]
    listaPermisos = listaPermisos + PERMISOS_CLIENTE + PERMISOS_USUARIO + PERMISOS_RESERVACONSOLA + PERMISOS_RESERVAVIDEOJUEGO

    return listaPermisos

STEAM_API_KEY ="2CFF66F3242D132079B04E158A7172B5"