version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gameheavendb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sisinf_C6
  web:
    build: .
    command: bash -c "python manage.py createsuperuser && python manage.py migrate && python manage.py runserver 0.0.0.0:25666"
    volumes:
      - .:/app
    ports:
      - "25666:25666"
