version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gameheavendb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sisinf_C6
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  
