# Generated by Django 4.2.6 on 2023-10-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameheaven', '0002_rename_user_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaconsola',
            name='estado',
            field=models.CharField(choices=[('Completada', 'No completada'), ('No completada', 'Completada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservavideojuego',
            name='estado',
            field=models.CharField(choices=[('Completada', 'No completada'), ('No completada', 'Completada')], max_length=50),
        ),
    ]
