# Generated by Django 4.2.6 on 2023-10-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameheaven', '0003_alter_reservaconsola_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='img',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='img',
            field=models.BinaryField(null=True),
        ),
    ]
