# Generated by Django 4.2.6 on 2023-10-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameheaven', '0004_alter_consola_img_alter_videojuego_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaconsola',
            name='estado',
            field=models.CharField(choices=[('No completada', 'Completada'), ('Completada', 'No completada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservavideojuego',
            name='estado',
            field=models.CharField(choices=[('No completada', 'Completada'), ('Completada', 'No completada')], max_length=50),
        ),
    ]
