# Generated by Django 4.2.6 on 2023-11-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameheaven', '0005_alter_reservaconsola_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaconsola',
            name='estado',
            field=models.CharField(choices=[('No completada', 'No completada'), ('Completada', 'Completada')], default='No completada', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservavideojuego',
            name='estado',
            field=models.CharField(choices=[('No completada', 'No completada'), ('Completada', 'Completada')], default='No completada', max_length=50),
        ),
    ]
