# Generated by Django 4.1.7 on 2023-10-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=500, null=True)),
                ('img', models.ImageField(null=True, upload_to='img/')),
                ('valoracion', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('codigoPostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=500, null=True)),
                ('valoracion', models.FloatField(null=True)),
                ('plataformas', models.CharField(max_length=50, null=True)),
                ('img', models.ImageField(null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('idAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.administrador')),
                ('idTienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='StockVideojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.tienda')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.videojuego')),
            ],
        ),
        migrations.CreateModel(
            name='StockConsolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.consola')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaVideojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('estadoCompletada', 'Completada'), ('estadoNoCompletada', 'No completada')], max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.cliente')),
                ('videojuegoTienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.stockvideojuego')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaConsola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('estadoCompletada', 'Completada'), ('estadoNoCompletada', 'No completada')], max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.cliente')),
                ('consolaTienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.stockconsolas')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='idTienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.tienda'),
        ),
    ]
