# Generated by Django 4.1.7 on 2023-10-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(max_length=500, null=True)),
                ('valoracion', models.FloatField(null=True)),
                ('img', models.ImageField(null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='StockConsola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.consola')),
            ],
        ),
        migrations.CreateModel(
            name='StockVideojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('codigoPostal', models.IntegerField()),
                ('consolas', models.ManyToManyField(through='gameheaven.StockConsola', to='gameheaven.consola')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(max_length=500, null=True)),
                ('valoracion', models.FloatField(null=True)),
                ('plataformas', models.CharField(max_length=50, null=True)),
                ('img', models.ImageField(null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.administrador')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.tienda')),
            ],
        ),
        migrations.AddField(
            model_name='tienda',
            name='videojuegos',
            field=models.ManyToManyField(through='gameheaven.StockVideojuego', to='gameheaven.videojuego'),
        ),
        migrations.AddField(
            model_name='stockvideojuego',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.tienda'),
        ),
        migrations.AddField(
            model_name='stockvideojuego',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.videojuego'),
        ),
        migrations.AddField(
            model_name='stockconsola',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.tienda'),
        ),
        migrations.CreateModel(
            name='ReservaVideojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('No completada', 'Completada'), ('Completada', 'No completada')], max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.cliente')),
                ('stockVideojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.stockvideojuego')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaConsola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('No completada', 'Completada'), ('Completada', 'No completada')], max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.cliente')),
                ('stockConsola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.stockconsola')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.tienda'),
        ),
        migrations.AddConstraint(
            model_name='stockvideojuego',
            constraint=models.UniqueConstraint(fields=('tienda', 'videojuego'), name='unique_videojuego_tienda'),
        ),
        migrations.AddConstraint(
            model_name='stockconsola',
            constraint=models.UniqueConstraint(fields=('tienda', 'consola'), name='unique_consola_tienda'),
        ),
    ]
