# Generated by Django 4.1.7 on 2023-10-21 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TRABAJADOR', 'Trabajador'), ('CLIENTE', 'Cliente')], default='ADMIN', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(max_length=500, null=True)),
                ('valoracion', models.FloatField(null=True)),
                ('img', models.ImageField(null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='StockConsola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.consola')),
            ],
        ),
        migrations.CreateModel(
            name='StockVideojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(max_length=500, null=True)),
                ('valoracion', models.FloatField(null=True)),
                ('plataformas', models.CharField(max_length=50, null=True)),
                ('img', models.ImageField(null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('gameheaven.customuser',),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('gameheaven.customuser',),
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('codigoPostal', models.IntegerField()),
                ('consolas', models.ManyToManyField(through='gameheaven.StockConsola', to='gameheaven.consola')),
                ('videojuegos', models.ManyToManyField(through='gameheaven.StockVideojuego', to='gameheaven.videojuego')),
            ],
        ),
        migrations.AddField(
            model_name='stockvideojuego',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.tienda'),
        ),
        migrations.AddField(
            model_name='stockvideojuego',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.videojuego'),
        ),
        migrations.AddField(
            model_name='stockconsola',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.tienda'),
        ),
        migrations.CreateModel(
            name='ReservaVideojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('No completada', 'Completada'), ('Completada', 'No completada')], max_length=50)),
                ('stockVideojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.stockvideojuego')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaConsola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('No completada', 'Completada'), ('Completada', 'No completada')], max_length=50)),
                ('stockConsola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.stockconsola')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameheaven.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajadorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.tienda')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.trabajador')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stockvideojuego',
            constraint=models.UniqueConstraint(fields=('tienda', 'videojuego'), name='unique_videojuego_tienda'),
        ),
        migrations.AddConstraint(
            model_name='stockconsola',
            constraint=models.UniqueConstraint(fields=('tienda', 'consola'), name='unique_consola_tienda'),
        ),
        migrations.AddField(
            model_name='reservavideojuego',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.cliente'),
        ),
        migrations.AddField(
            model_name='reservaconsola',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.cliente'),
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gameheaven.cliente'),
        ),
    ]
