# Generated by Django 4.2.6 on 2023-10-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gameheaven', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='reservaconsola',
            name='estado',
            field=models.CharField(choices=[('Completada', 'No completada'), ('No completada', 'Completada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservavideojuego',
            name='estado',
            field=models.CharField(choices=[('Completada', 'No completada'), ('No completada', 'Completada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='codigoPostal',
            field=models.IntegerField(unique=True),
        ),
    ]
