# Generated by Django 4.2.6 on 2023-10-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameheaven', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='consola',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reservaconsola',
            name='estado',
            field=models.CharField(choices=[('No completada', 'Completada'), ('Completada', 'No completada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservavideojuego',
            name='estado',
            field=models.CharField(choices=[('No completada', 'Completada'), ('Completada', 'No completada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='stockconsola',
            unique_together={('tienda', 'consola')},
        ),
        migrations.AlterUniqueTogether(
            name='stockvideojuego',
            unique_together={('tienda', 'videojuego')},
        ),
    ]
