# Generated by Django 4.1.7 on 2023-10-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameheaven', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='consolas',
            field=models.ManyToManyField(through='gameheaven.StockConsolas', to='gameheaven.consola'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='videojuegos',
            field=models.ManyToManyField(through='gameheaven.StockVideojuego', to='gameheaven.videojuego'),
        ),
        migrations.AlterField(
            model_name='reservaconsola',
            name='estado',
            field=models.CharField(choices=[('estadoNoCompletada', 'No completada'), ('estadoCompletada', 'Completada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservavideojuego',
            name='estado',
            field=models.CharField(choices=[('estadoNoCompletada', 'No completada'), ('estadoCompletada', 'Completada')], max_length=50),
        ),
    ]
