# Generated by Django 4.2.6 on 2023-10-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameheaven', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaconsola',
            name='estado',
            field=models.CharField(choices=[('No completada', 'Completada'), ('Completada', 'No completada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservavideojuego',
            name='estado',
            field=models.CharField(choices=[('No completada', 'Completada'), ('Completada', 'No completada')], max_length=50),
        ),
    ]
