# Generated by Django 4.2.6 on 2023-10-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameheaven', '0002_alter_administrador_email_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockconsola',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stockvideojuego',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stockconsola',
            constraint=models.UniqueConstraint(fields=('tienda', 'consola'), name='unique_consola_tienda'),
        ),
        migrations.AddConstraint(
            model_name='stockvideojuego',
            constraint=models.UniqueConstraint(fields=('tienda', 'videojuego'), name='unique_videojuego_tienda'),
        ),
    ]
