# Generated by Django 4.2.6 on 2023-11-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameheaven', '0006_alter_reservaconsola_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='steamID',
            field=models.IntegerField(null=True),
        ),
    ]
